node_sets {
    key: "atom"
    value { 
        description: "An atom."
    
        features: {
            key: "atom_num"
            value: {
                description: "The atom number."
                dtype: DT_INT64
            }
        }
    }
    key: "_readout"
        value{
            description: "the readout nodes."

            features: {
                key:"Shift"
                value: {
                description: "The chemical shift of the atom."
                dtype: DT_FLOAT
            }
        }
}

edge_sets {
    key: "bond"
    value {
        description: "An atom bond."
        source: "atom"
        target: "atom"

        features: {
            key: "bond_type"
            value: {
                description: "The type of bond (single, double, etc.)."
                dtype: DT_INT64
            }
        }
        features: {
            key: "distance"
            value: {
                description: "The interatomic distance."
                dtype: DT_FLOAT
            }
        }
    }
    key: "hydrogen"
    value {
        description: "Edges marking the hydrogen atoms for readout"
        source: "atom"
        target: "_readout"
    }
}

context {
    features {
        key: "smiles"
        value: {
            description: "The smiles of the molecule."
            dtype: DT_STRING
        }
    }
}