wandb_version: 1

learning_rate:
  desc: null
  value: 0.0005
dataset:
  desc: null
  value: cascade
epochts:
  desc: null
  value: 1200
setting:
  desc: null
  value: default
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.16.2
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705925151.693883
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      4: 3.7.16
      5: 0.16.2
      8:
      - 5
      10:
      - 9
      13: linux-x86_64
